# Generated by Django 4.0 on 2023-07-19 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('appOne', '0002_alter_profile_cuvertureimg_alter_profile_profileimg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='profile',
        ),
        migrations.AddField(
            model_name='posts',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
    ]
