# Generated by Django 4.0 on 2023-07-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0003_remove_posts_profile_posts_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
