# Generated by Django 4.0 on 2023-07-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0006_posts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
