# Generated by Django 4.0 on 2023-07-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0007_alter_posts_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
