# Generated by Django 4.0 on 2023-07-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0010_posts_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='createdAt',
        ),
    ]
