# Generated by Django 4.0 on 2023-07-19 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0012_posts_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
