# Generated by Django 4.0 on 2023-07-20 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0014_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('friends', models.ManyToManyField(to='appOne.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.AlterField(
            model_name='posts',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appOne.user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appOne.user'),
        ),
    ]
