# Generated by Django 4.0 on 2023-07-21 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('appOne', '0018_alter_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appOne.posts')),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
    ]
