# Generated by Django 4.0 on 2023-07-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0019_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.IntegerField(max_length=50000, null=True),
        ),
    ]
