# Generated by Django 4.0 on 2023-07-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0021_alter_comments_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.IntegerField(null=True),
        ),
    ]
