# Generated by Django 4.0 on 2023-08-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0028_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
