# Generated by Django 4.0 on 2023-08-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0031_rooms_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
