# Generated by Django 4.0 on 2023-08-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('appOne', '0034_messages_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='userOne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user1', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='userTwo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user2', to='auth.user'),
        ),
    ]
