# Generated by Django 4.0 on 2023-08-06 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0037_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='Post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appOne.posts'),
        ),
    ]
