# Generated by Django 4.0 on 2024-03-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0039_remove_notifications_post_notifications_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cuvertureImg',
            field=models.ImageField(default='grey.jfif', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileImg',
            field=models.ImageField(default='person.png', upload_to='img'),
        ),
    ]
